sudo: false
language: php

php:
 - 5.6
 - 7.0

cache:
 directories:
  - $HOME/.composer/cache/files
install:
 - phpenv config-rm xdebug.ini
before_script:
 - composer update --prefer-dist
 - echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit
